---
title: "PROJECT"
author: "Peng Yi Ting"
date: "2018年11月14日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#openapi/r crawler
#library packages
library(rvest)
library(XML)
library(xml2)
library(bitops)
library(RCurl)
library(httr)
```

```{r}
#get HTML/ only one page
jong.html <-paste("https://www.ptt.cc/bbs/LeeJongSuk/index58.html")
jong.title <- html_nodes(read_html(jong.html),".title a" )
jong.title
jong.hrefs <- html_attr(jong.title, 'href')
jong.titletext<-html_text(jong.title)
jong.titletext
for(i in jong.titletext){
  print(i)}
```

```{r}
# form a empty vector
jong.article.data <- c()

for(i in 1:length(jong.hrefs)){
  # paste0() ==> without any white space
  article.url <- paste0('https://www.ptt.cc', jong.hrefs[i])
  article <- html_nodes(read_html(article.url), "#main-content")
  article.content <- html_text(article)
  
  
  article.utf8 <- iconv(article.content, 'utf8')
  # vector start counting from 1!!
  jong.article.data <- c(jong.article.data, article.utf8)
  # Suspend execution of R expressions for a specified time interval.
  # Sys.sleep(sample(3:5, 1))
}
jong.article.data[1]
View(jong.article.data)
str(article.utf8)
str(jong.article.data)
```

```{r}
#斷詞
library("jiebaRD")
library("jiebaR")
library(tm)

```

```{r}

Sys.setlocale(category = "LC_ALL", locale = "cht")
cc <- worker()
new_user_word(cc,words = "鍾碩","n")
new_user_word(cc,words = "姜哲和妍珠","n")
new_user_word(cc,words = "當你沉睡時","n")
new_user_word(cc,words = "聽見你的聲音","n")
new_user_word(cc,words = "批踢踢","n")
new_user_word(cc,words = "宰璨","n")
new_user_word(cc,words = "搜查官","n")
new_user_word(cc,words = "哎一古","n")
new_user_word(cc,words = "祕密花園","n")
cc[jong.article.data]
jong<-table(cc[jong.article.data])
jong
jong<-data.frame(jong)
jong<-jong[order(jong$Freq,decreasing = T),]
head(jong)

```

```{r}
#get a wordcloud

library(wordcloud2)
wordcloud2(jong)
```
