---
title: "hw_week3"
author: "Peng Yi Ting"
date: "2018年10月3日"
output: html_document
---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install and libary ggplot

```{r}
library(ggplot2)

```

### Using data: 
2001-2017 15歲以上民間人口之教育程度結構：國中程度以下/高中程度/大專程度以上
```{r}
newtaipei<-read.csv(file="newtaipeicity.csv", header= T, sep= ",")
View(newtaipei)
heading<- c("year", "ratio1", "ratio2","ratio3" )
names(newtaipei)<-heading
newtaipei
str(newtaipei)
as.character(newtaipei$year)
summary(newtaipei)
```

### Plot a barchart 
```{r}
ggplot(newtaipei, aes(x=year, y=ratio1))+geom_bar(stat="identity", width=.5, fill="tomato1") + 
  labs(title="Ratio of under-junior-high-school level in New Taipei City", 
       x="YEAR",
       y="RATIO OF UNDER-JUNIOR-HIGH-SCHOOL LEVEL(%)",
  subtitle="Year Vs Ratio", 
  caption="source: 內政部統計資料庫")

ggplot(newtaipei, aes(x=year, y=ratio2))+geom_bar(stat="identity", width=.5, fill="tomato2") + 
  labs(title="Ratio of high-school level in New Taipei City", 
       x="YEAR",
       y="RATIO OF HIGH-SCHOOL LEVEL(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料庫")

ggplot(newtaipei, aes(x=year, y=ratio3))+geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ratio of above-unversity level in New Taipei City", 
       x="YEAR",
       y="RATIO OF ABOBE-UNVERSITY LEVEL(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料庫")
```

