---
title: "hw_week3"
author: "Peng Yi Ting"
date: "2018年10月3日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Install and libary ggplot2
1. 下載ggplot2 package
```{r}
#install and libary ggplot
#install.packages('ggplot2')
library(ggplot2)
```

###Read data
2. 讀取資料:
2001-2017年新北市區域15歲以上教育程度結構-國中及以下/高中/大專及以上
```{r}
#read data and setting
newtaipei<-read.csv(file="newtaipeicity.csv", header= T, sep= ",")
View(newtaipei)
heading<- c("year", "ratio1", "ratio2","ratio3" )
names(newtaipei)<-heading
str(newtaipei)
as.character(newtaipei$year)
newtaipei
summary(newtaipei)
```

### Plot a barchart 
3. 畫圖表:

i. 國中及以下教育程度比例
```{r}
ggplot(newtaipei, aes(x=year, y=ratio1))+geom_bar(stat="identity", width=.5, fill="tomato1") + 
  labs(title="Ratio of under-junior-high-school level in New Taipei City", 
       x="Year",
       y="Ratio of Under-Junior-High-School Level(%)",
  subtitle="Year Vs Ratio", 
  caption="source: 內政部統計資料處")

```

ii. 高中教育程度比例
```{r}

ggplot(newtaipei, aes(x=year, y=ratio2))+geom_bar(stat="identity", width=.5, fill="tomato2") + 
  labs(title="Ratio of high-school level in New Taipei City", 
       x="Year",
       y="Ratio of High-School Level(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料處")
```

iii. 大專及以上教育程度比例
```{r}
ggplot(newtaipei, aes(x=year, y=ratio3))+
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ratio of above-unversity level in New Taipei City", 
       x="Year",
       y="Ratio of Above-Unverstity Level(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料處")
  
```

4.另外不同表示方式

i. 國中及以下教育程度比例
```{r}
theme_set(theme_classic())
ggplot(newtaipei, aes(x=year, y=ratio1))+
  geom_bar(stat="identity", aes(fill=ratio1), width = 0.5, position="stack") + 
  labs(title="Ratio of under-junior-high-school level in New Taipei City", 
       x="Year",
       y="Ratio of Under-Junior-High-School Level(%)",
  subtitle="Year Vs Ratio", 
  caption="source: 內政部統計資料處")
```

ii. 高中教育程度比例
```{r}
ggplot(newtaipei, aes(x=year, y=ratio2))+
  geom_bar(stat="identity", aes(fill=ratio2), width = 0.5, position="stack") + 
  labs(title="Ratio of high-school level in New Taipei City", 
       x="Year",
       y="Ratio of High-School Level(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料處")
```

iii. 大專及以上教育程度比例
```{r}
ggplot(newtaipei, aes(x=year, y=ratio3))+
  geom_bar(stat="identity", aes(fill=ratio3), width = 0.5, position="stack") + 
  labs(title="Ratio of above-unversity level in New Taipei City", 
       x="Year",
       y="Ratio of Above-Unverstity Level(%)",
       subtitle="Year Vs Ratio", 
       caption="source: 內政部統計資料處")+
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```

###NEXT
5. 希望結合三張圖表形成SAME ONE (Still trying now)